name: Publish Storyshots

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: Publish Storyshots Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: eichelkrautadam
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: eichelkrautadam/storyshots
          tags: |
            type=sha
            type=semver,pattern={{version}},value=${{ github.ref_name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,amd64'

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          file: Dockerfile.storyshots
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update bundle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout main
          sed -i '/eichelkrautadam\/storyshots/c\    image: eichelkrautadam/storyshots:${{ github.ref_name }}' batect-bundle.yml
          git config --global user.name 'github_actions'
          git config --global user.email 'github_actions@users.noreply.github.com'
          git add batect-bundle.yml
          git commit --amend --no-edit
          git tag --force ${{ github.ref_name }} HEAD
          git push -f origin HEAD:main
          git push --force --tags
