name: Publish Storyshots

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
jobs:

  test:
    name: Test Storyshots
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up PNPM
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.17.1

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install PNPM packages
        run: pnpm install --frozen-lockfile

      - name: Install shellspec
        run: curl -fsSL https://git.io/shellspec | sh -s -- --yes

      - name: Run Storyshots Tests
        run: |
          pnpm test:local

  publish:
    name: Push CI Image to Docker Hub
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: eichelkrautadam
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: eichelkrautadam/storyshots
          tags: |
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.storyshots
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
