name: Publish Storyshots

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: Publish Storyshots Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: eichelkrautadam
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: eichelkrautadam/storyshots
          tags: |
            type=sha
            type=semver,pattern={{version}},value=${{ github.ref_name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.storyshots
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update bundle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sed -i '/eichelkrautadam\/storyshots/c\    image: eichelkrautadam/storyshots:${{ github.ref_name }}' batect-bundle.yml
          git config --global user.name 'Github Actions'
          git config --global user.email 'githubactions@users.noreply.github.com'
          git add batect-bundle.yml
          git commit -m "ci: update bundle to ${{ github.ref_name }}"
          git push -u origin main
