name: Create Storyshots Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - batect-bundle.yml
jobs:

  test_and_release:
    name: Test and Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.head_ref }}

      - name: Set up PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install PNPM packages
        run: pnpm install --frozen-lockfile

      - name: Install shellspec
        run: curl -fsSL https://git.io/shellspec | sh -s -- --yes

      - name: Run Storyshots Tests
        run: |
          pnpm test:local

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-results
          path: test-results-local/**/*
          retention-days: 3

      - name: Automate Github Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
        run: |
          npx --package conventional-changelog-conventionalcommits@5.0.0 --package semantic-release@19.0.5 semantic-release
